"""Compatibility exports for candidate tagging tools."""

from lorakit.tools.tagging import (
    CAPTION_PRESETS,
    CandidateTag,
    CaptionEditor,
    CompositeTagger,
    FlorencePromptGenTagger,
    ImageTagger,
    PipelineSmilingWolfTagger,
    PipelineTagger,
    QwenVLTagJudge,
    RAMPlusTagger,
    SmilingWolfTag,
    SmilingWolfTagger,
    TaggingResult,
    TagRequest,
    build_source_tags,
    build_tagger,
    candidates_from_context,
    candidates_from_pipeline_smilingwolf,
    candidates_from_qwen_semantic,
    candidates_from_ram,
    clean_caption_output,
    extract_json_object,
    make_candidate,
    merge_candidates,
    merge_caption,
    merge_tags,
    metadata_has_tags,
    normalize_candidate_tag,
    source_authority,
    unique_preserve_order,
)


__all__ = [
    "CAPTION_PRESETS",
    "CandidateTag",
    "CaptionEditor",
    "CompositeTagger",
    "FlorencePromptGenTagger",
    "ImageTagger",
    "PipelineSmilingWolfTagger",
    "PipelineTagger",
    "QwenVLTagJudge",
    "RAMPlusTagger",
    "SmilingWolfTag",
    "SmilingWolfTagger",
    "TaggingResult",
    "TagRequest",
    "build_source_tags",
    "build_tagger",
    "candidates_from_context",
    "candidates_from_pipeline_smilingwolf",
    "candidates_from_qwen_semantic",
    "candidates_from_ram",
    "clean_caption_output",
    "extract_json_object",
    "make_candidate",
    "merge_candidates",
    "merge_caption",
    "merge_tags",
    "metadata_has_tags",
    "normalize_candidate_tag",
    "source_authority",
    "unique_preserve_order",
]
